variables:
- name: linux-latest
  value: 'ubuntu-20.04'
- name: linux-previous
  value: 'ubuntu-18.04'
- name: vs-latest
  value: 'windows-latest'
- name: vs-previous
  value: 'vs2017-win2016'
- name: xcode-latest
  value: macos-10.15
- name: xcode-previous
  value: macOS-10.14

# GCC
stages:
- stage: GCC
  dependsOn: []
  variables:
  - name: CC
    value: gcc
  - name: CXX
    value: g++
  jobs:
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate GCC latest'
      imageName: ${{ variables.linux-latest }}
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate GCC Previous'
      imageName: ${{ variables.linux-previous }}

# Clang
- stage: Clang
  dependsOn: []
  variables:
  - name: CC
    value: clang
  - name: CXX
    value: clang++
  jobs:
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate Clang latest'
      imageName: ${{ variables.linux-latest }}
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate Clang Previous'
      imageName: ${{ variables.linux-previous }}

# MSVC
- stage: MSVC
  dependsOn: []
  jobs:
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate MSVC latest'
      imageName: ${{ variables.vs-latest }}
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate MSVC Previous'
      imageName: ${{ variables.vs-previous }}

# Apple-Clang
- stage: Apple_Clang
  dependsOn: []
  jobs:
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate Apple-Clang latest'
      imageName: ${{ variables.xcode-latest }}
  - template: ./pipelines/jobs.yml
    parameters:
      jobName: 'Validate Apple-Clang Previous'
      imageName: ${{ variables.xcode-previous }}
