pr:
  autoCancel: true

variables:
- name: ubuntu-latest
  value: 'ubuntu-20.04'
- name: ubuntu-previous
  value: 'ubuntu-18.04'
- name: vs-latest
  value: 'windows-latest'
- name: vs-previous
  value: 'vs2017-win2016'
- name: xcode-latest
  value: macos-11.0
- name: xcode-previous
  value: macOS-10.15

# GCC
stages:
- stage: GCC
  dependsOn: []
  variables:
  - name: CC
    value: gcc
  - name: CXX
    value: g++
  jobs:
  - job:
    displayName: Validate GCC latest
    pool:
      vmImage: $(ubuntu-latest)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    continueOnError: false
    steps:
    - template: ./pipelines/steps.yml

  - job:
    displayName: Validate GCC Previous
    pool:
      vmImage: $(ubuntu-previous)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    continueOnError: false
    steps:
    - template: ./pipelines/steps.yml

# Clang
- stage: Clang
  dependsOn: []
  variables:
  - name: CC
    value: clang
  - name: CXX
    value: clang++
  jobs:
  - job:
    displayName: Validate Clang latest
    pool:
      vmImage: $(ubuntu-latest)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    continueOnError: false
    steps:
    - template: ./pipelines/steps.yml

  - job:
    displayName: Validate Clang previous
    pool:
      vmImage: $(ubuntu-previous)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    continueOnError: false
    steps:
    - template: ./pipelines/steps.yml

# MSVC
- stage: MSVC
  dependsOn: []
  jobs:
  - job:
    displayName: Validate MSVC latest
    pool:
      vmImage: $(vs-latest)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    steps:
    - template: ./pipelines/steps.yml

  - job:
    displayName: Validate MSVC previous
    pool:
      vmImage: $(vs-previous)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    steps:
    - template: ./pipelines/steps.yml

# Apple-Clang
- stage: Apple_Clang
  dependsOn: []
  jobs:
  - job:
    displayName: Validate Apple-Clang latest
    pool:
      vmImage: $(xcode-latest)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    steps:
    - template: ./pipelines/steps.yml

  - job:
    displayName: Validate Apple-Clang previous
    pool:
      vmImage: $(xcode-previous)
    strategy:
      matrix:
        14_debug:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Debug'
        14_release:
          GSL_CXX_STANDARD: '14'
          BUILD_TYPE: 'Release'
        17_debug:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Debug'
        17_release:
          GSL_CXX_STANDARD: '17'
          BUILD_TYPE: 'Release'
    steps:
    - template: ./pipelines/steps.yml
