trigger:
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

jobs:
  - job: Windows
    steps:
    - template: azure_pipelines/windows.yml

  - job: Linux
    steps:
    - template: azure_pipelines/linux.yml

  - job: MacOS
    steps:
    - template: azure_pipelines/mac.yml
