trigger:
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

strategy:
  maxParallel: 10
  matrix:
    # # current clang
    # clang-current-14-debug:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # clang-current-14-release:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # clang-current-17-debug:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # clang-current-17-release:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # # previous clang
    # clang-previous-14-debug:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # clang-previous-14-release:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # clang-previous-17-debug:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # clang-previous-17-release:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'clang'
    #   CXX: 'clang++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # # current g++
    # gcc-current-14-debug:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # gcc-current-14-release:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # gcc-current-17-debug:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # gcc-current-17-release:
    #   imageName: 'ubuntu-20.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # # previous g++
    # gcc-previous-14-debug:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # gcc-previous-14-release:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # gcc-previous-17-debug:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # gcc-previous-17-release:
    #   imageName: 'ubuntu-18.04'
    #   CC: 'gcc'
    #   CXX: 'g++'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # # current vs
    # vs_latest_14_debug:
    #   imageName: windows-latest
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # vs_latest_14_release:
    #   imageName: windows-latest
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # vs_latest_17_debug:
    #   imageName: windows-latest
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # vs_latest_17_release:
    #   imageName: windows-latest
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # # previous vs
    # vs_previous_14_debug:
    #   imageName: vs2017-win2016
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # vs_previous_14_release:
    #   imageName: vs2017-win2016
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # vs_previous_17_debug:
    #   imageName: vs2017-win2016
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # vs_previous_17_release:
    #   imageName: vs2017-win2016
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # current xcode
    xcode_latest_14_debug:
      imageName: macOS-latest
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Debug'
    xcode_latest_14_release:
      imageName: macOS-latest
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Release'
    xcode_latest_17_debug:
      imageName: macOS-latest
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Debug'
    xcode_latest_17_release:
      imageName: macOS-latest
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Release'

    # previous xcode
    xcode_previous_14_debug:
      imageName: macOS-10.14
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Debug'
    xcode_previous_14_release:
      imageName: macOS-10.14
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Release'
    xcode_previous_17_debug:
      imageName: macOS-10.14
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Debug'
    xcode_previous_17_release:
      imageName: macOS-10.14
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Release'

pool:
  vmImage: $(imageName)

steps:
  - task: CMake@1
    name: Configure
    inputs:
      workingDirectory: build
      cmakeArgs: '-DCMAKE_CXX_STANDARD=$(GSL_CXX_STANDARD) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) .. '

  - task: CMake@1
    name: Build
    inputs:
      workingDirectory: build
      cmakeArgs: '--build . '

  - script: ctest . --output-on-failure --no-compress-output
    name: CTest
    workingDirectory: build
    failOnStderr: true

