trigger:
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master
# CXX: 'g++'
# CXX: 'g++-9'
# CXX: 'clang++'
# CXX: 'clang++-10'
# GSL_CXX_STANDARD: '14'
# GSL_CXX_STANDARD: '17'
# BUILD_TYPE: 'Debug'
# BUILD_TYPE: 'Release'
strategy:
  matrix:

    # Latest g++
    linux-current-gcc-latest-14-debug:
      imageName: 'ubuntu-latest'
      CC: 'gcc'
      CXX: 'g++'
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Debug'
    linux-current-gcc-latest-14-release:
      imageName: 'ubuntu-latest'
      CC: 'gcc'
      CXX: 'g++'
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Release'
    linux-current-gcc-latest-17-debug:
      imageName: 'ubuntu-latest'
      CC: 'gcc'
      CXX: 'g++'
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Debug'
    linux-current-gcc-latest-17-release:
      imageName: 'ubuntu-latest'
      CC: 'gcc'
      CXX: 'g++'
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Release'

    # # Previous g++
    # linux-current-gcc-previous-14-debug:
    #   imageName: 'ubuntu-latest'
    #   CC: 'gcc'
    #   CXX: 'g++-9'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # linux-current-gcc-previous-14-release:
    #   imageName: 'ubuntu-latest'
    #   CC: 'gcc'
    #   CXX: 'g++-9'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # linux-current-gcc-previous-17-debug:
    #   imageName: 'ubuntu-latest'
    #   CC: 'gcc'
    #   CXX: 'g++-9'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # linux-current-gcc-previous-17-release:
    #   imageName: 'ubuntu-latest'
    #   CC: 'gcc'
    #   CXX: 'g++-9'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

    # Latest clang
    linux-current-clang-latest-14-debug:
      imageName: 'ubuntu-latest'
      CC: 'clang'
      CXX: 'clang++'
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Debug'
    linux-current-clang-latest-14-release:
      imageName: 'ubuntu-latest'
      CC: 'clang'
      CXX: 'clang++'
      GSL_CXX_STANDARD: '14'
      BUILD_TYPE: 'Release'
    linux-current-clang-latest-17-debug:
      imageName: 'ubuntu-latest'
      CC: 'clang'
      CXX: 'clang++'
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Debug'
    linux-current-clang-latest-17-release:
      imageName: 'ubuntu-latest'
      CC: 'clang'
      CXX: 'clang++'
      GSL_CXX_STANDARD: '17'
      BUILD_TYPE: 'Release'

    # Previous clang
    # linux-current-clang-previous-14-debug:
    #   imageName: 'ubuntu-latest'
    #   CC: 'clang'
    #   CXX: 'clang++-10'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Debug'
    # linux-current-clang-laprevioustest-14-release:
    #   imageName: 'ubuntu-latest'
    #   CC: 'clang'
    #   CXX: 'clang++-10'
    #   GSL_CXX_STANDARD: '14'
    #   BUILD_TYPE: 'Release'
    # linux-current-clang-previous-17-debug:
    #   imageName: 'ubuntu-latest'
    #   CC: 'clang'
    #   CXX: 'clang++-10'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Debug'
    # linux-current-clang-previous-17-release:
    #   imageName: 'ubuntu-latest'
    #   CC: 'clang'
    #   CXX: 'clang++-10'
    #   GSL_CXX_STANDARD: '17'
    #   BUILD_TYPE: 'Release'

pool:
  vmImage: $(imageName)
    # # Latest XCode
    # mac-current:
    #   imageName: 'macOS-latest'

    # # Previous XCode
    # mac-previous:
    #   imageName: 'macOS-10.14'

    # # Latest VS
    # windows-current:
    #   imageName: 'windows-latest'

    # # Previous VS
    # windows-previous:
    #   imageName: 'vs2017-win2016'

steps:
  - script: |
      echo $(imageName)
      echo $(CXX)
      echo $(GSL_CXX_STANDARD)
      echo $(BUILD_TYPE)
      $(CXX) --version

  - task: CMake@1
    name: Configure
    inputs:
      workingDirectory: build
      cmakeArgs: '-DCMAKE_BUILD_TYPE=$(BUILD_TYPE) .. '

  - task: CMake@1
    name: Build
    inputs:
      workingDirectory: build
      cmakeArgs: '--build . '

  - script: |
      ctest ./build

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
# jobs:
#   - template: nix_build.yml
#     parameters:
#       name: Linux Current
#       vmImage: 'ubuntu-latest'
#       conf: 'Debug'
#       GSL_CXX_STANDARD: '14'
#       CXX: g++
